import type { CopyDictionary } from "./zh-CN";

const enUS: CopyDictionary = {
  desktopProviders: {
    description: "Desktop keeps keys in Windows Credential Manager. Saved provider settings do not contain plain-text keys.",
    defaultSelection: "Using the default model provider settings.",
    onboardingHint: "Continue to enter your key in a secure system window. Settings are saved only after the connection test succeeds.",
    preset: "Use SiliconFlow preset",
    compatible: "OpenAI-compatible",
    credentialHint: "Windows collects the key in a secure window, outside web forms and browser storage.",
    verifying: "Verifying…",
    saveVerify: "Save & verify",
    verified: "Verified and saved {{label}}. Now using {{model}}.",
    connected: "Connected to {{label}}. The model list is available.",
    modelsLoaded: "Loaded {{count}} models for {{label}}.",
    selected: "Selected {{label}} · {{model}}.",
    removed: "Model provider settings removed.",
    probeSummary: "Connection test: {{count}} models available · Incremental replies: {{streaming}} · Tool use: {{tools}} · Usage tracking: {{usage}}",
    supported: "Supported",
    unsupported: "Not supported",
    models: "Available models: {{models}}",
    empty: "No model providers configured. Add one above to get started.",
    active: " (active)",
    noDefaultModel: "No default model",
    selecting: "Selecting…",
    reconfigure: "Reconfigure",
    remove: "Remove",
    credentialKeyring: "Key saved in system storage",
    credentialEnv: "Key from environment variable",
    credentialFile: "Key from local file",
    credentialNone: "No key configured",
  },
  artifactLabels: {
    report: "Run report",
    task_state: "Task progress",
    trace: "Activity log",
    registered: "Run-generated file",
    tool_artifact: "Tool-generated file",
    available: "Available",
    cleaned: "Content removed",
    invalid: "Content could not be verified",
    too_large: "Large file — download to view",
  },
  review: {
    title: "Read-only Review",
    refresh: "Refresh Reviews",
    cancel: "Cancel Review",
    loading: "Loading Reviews…",
    empty: "No Review runs",
    emptyBody: "Start a Review from the composer to inspect a Git target without changing it.",
    run: "Review run",
    target: "Target",
    files: "Files",
    findings: "Findings",
    unchecked: "Unchecked",
    warnings: "Warnings",
    passBody: "No actionable findings were reported.",
    loadingFindings: "Loading findings…",
    unavailableFindings: "Finding details are unavailable.",
    openFiles: "Open in Files",
    more: "Load more findings",
    partialBody: "Some portions were not checked. Review the coverage before acting.",
    staleBody: "The target changed or needs attention. Start a new Review for the current files.",
    unavailableBody: "The Review target or service is unavailable.",
    cancelledBody: "Review was cancelled before completion.",
    errorBody: "Review failed. No chat turn was changed.",
    error: "The Review action could not be completed. Refresh and retry.",
    warningBody: "This Review has warnings. Check its coverage before relying on the results.",
    unknown: "Unknown",
    status_queued: "Queued",
    status_running: "Running",
    status_pass: "Passed",
    status_findings: "Findings",
    status_partial: "Partial",
    status_stale: "Target changed",
    status_needs_attention: "Needs attention",
    status_unavailable: "Unavailable",
    status_cancelled: "Cancelled",
    status_error: "Failed",
  },
  chrome: {
    loadError: "The action could not be completed. Refresh and retry.",
    partial: "Some records could not be loaded.",
    download: "Download {{name}}",
    previewUnavailable: "Preview is unavailable for this type.",
    previewHtmlOpen: "Open in isolated preview",
    previewHtmlClose: "Close isolated preview",
    previewHtmlHint: "HTML can execute in an isolated origin; the preview page cannot read product credentials.",
    previewHtmlActive: "Isolated preview session is open; its token is revoked on close.",
    invalidContent: "This content cannot be previewed safely.",
    cleaned: "Artifact data has been cleaned.",
    format: "Format",
    offlineHtml: "Offline HTML",
    refreshDiff: "Refresh diff",
    noPatch: "No patch was recorded.",
    binary: "Binary file",
    truncated: "Partial content",
    fullPatch: "Full patch",
    summaryOnly: "Summary only",
    directory: "Folder",
    loadMore: "Load more",
    scanLimited: "This directory is large; only results within the safety limit are shown.",
    advanced: "Advanced",
    cancelEdit: "Cancel edit",
    models: "Available models ({{count}})",
    removeProvider: "Remove this provider profile? Sessions will not be deleted.",
    settingsError: "The settings action could not be completed. Check the current settings and retry.",
    providerError: "The provider action could not be completed. Check the connection and settings, then retry.",
  },
  common: {
    retry: "Retry",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    close: "Close",
    back: "Back",
    loading: "Loading…",
    none: "None",
    noSavedProfiles: "No saved profiles yet.",
    more: "More",
    actions: "Actions",
    dismiss: "Got it",
    copy: "Copy",
    copied: "Copied",
  },
  connection: {
    ok: "API connected",
    error: "API unreachable",
    checking: "Checking API…",
  },
  theme: {
    toLight: "Switch to light theme",
    toDark: "Switch to dark theme",
  },
  locale: {
    label: "Language",
    zhCN: "中文",
    enUS: "English",
  },
  nav: {
    settings: "Settings",
    backToChat: "Back to chat",
    workspace: "Workspace",
    expandWorkspace: "Expand workspace list",
    collapseWorkspace: "Collapse workspace list",
    inspector: "Details",
    expandInspector: "Expand details",
    collapseInspector: "Collapse details",
    closeInspector: "Close details",
    newSession: "New session",
    searchWorkspace: "Search sessions",
  },
  chat: {
    responding: "Responding…",
    assistant: "Assistant",
    you: "You",
    send: "Send",
    sendUnexpectedError: "Could not confirm the send. Your draft is preserved; check the conversation before trying again.",
    stop: "Stop",
    placeholder: "Type a message. Ctrl/Cmd+Enter to send, Enter for a new line.",
    loadOlder: "Load earlier turns",
    restoring: "Restoring this conversation…",
    restorePartialTitle: "Partial conversation history",
    restorePartial:
      "Some earlier messages could not be restored. New messages are unaffected.",
    restoreFailed: "Conversation restore failed",
    restoreError: "No empty history has been substituted for the failed read.",
    restoreRetry: "Retry restore",
    startNewSession: "Start a new session",
    emptyTranscript: "Send a message to start a run in this session.",
    approve: "Approve",
    reject: "Reject",
    onlyThisTime: "Only this time",
    queue: "Queue",
    revoke: "Revoke",
    promote: "Send now",
    disabledRestoring: "Finishing restoring this conversation…",
    disabledSettings: "Session settings are loading…",
    disabledRestoreError: "Retry transcript restore before sending.",
    disabledRoute: "Resolve the product route before sending.",
    model: "Model",
    mode: "Mode",
    review: "Review",
    turn: "Turn {{n}}",
    currentTurn: "Current turn",
    inputSubmitted: "Input submitted",
    inputClosed: "Input closed",
    revokeTitle: "Revoke message",
    evidence: "Message usage and context",
    reviewTarget: "Target",
    reviewUncommitted: "Uncommitted changes",
    reviewBase: "Base revision",
    reviewCommit: "Commit",
    reviewStart: "Start review",
    reviewStarting: "Starting…",
    reviewRevision: "Review revision",
    reviewBasePlaceholder: "Base ref, e.g. main",
    reviewCommitPlaceholder: "Commit SHA",
    readingWidth: "Reading width (Left/Right arrows, double-click to reset)",
    readingWidthValue: "Reading width {{width}} pixels",
  },
  inspector: {
    title: "Details",
    tabsLabel: "Details tabs",
    tabNew: "New tab",
    tabPending: "Pending",
    tabStatus: "Run",
    tabFiles: "Files",
    tabChanges: "Changes",
    tabReview: "Review",
    openTab: "Open a tab",
    closeTab: "Close {{name}}",
    launcherTitle: "Open a tab",
    noTabs: "No tabs are open. Use + to open one.",
    approvalDetail: "Approval details",
    approvalSubmitting: "Submitting decision; awaiting server state…",
    approvalUnavailable: "This request is no longer pending in the current run. This does not confirm approval by this window or tool success.",
    panelWidth: "Panel width (Left/Right arrows, Home/End)",
    panelWidthValue: "Panel width {{width}} pixels",
    approvalScope: "Only the requested tool call. No permanent permission is granted.",
    sidebarWidth: "Navigation width (Left/Right arrows, Home/End)",
    sidebarWidthValue: "Navigation width {{width}} pixels",
    authorizationTitle: "This session's authorization requests",
    authorizationLoading: "Loading this session's authorization requests…",
    authorizationError: "Could not load this session's authorization requests.",
    authorizationNone: "No tool authorization requests were recorded for this session.",
    authorizationPartial: "The page was truncated; only the most recent authorization requests are shown.",
    authorizationHistoryNote:
      "Decision status and channel come from the durable record; fields that were never recorded read as unknown. A successful tool result does not mean this window approved it.",
    authorizationHistoryUnavailable:
      "The decision actor and time are not persisted yet, so they read as unknown; a successful tool result does not mean this window approved it.",
    authorizationColumnTool: "Tool",
    authorizationColumnCall: "Call ID",
    authorizationColumnScope: "Scope",
    authorizationColumnDecision: "Decision",
    authorizationColumnActor: "Decision channel",
    authorizationColumnTime: "Time",
    authorizationColumnOutcome: "Outcome",
    authorizationRun: "run {{ordinal}}",
    authorizationRunLabel: "linked run",
    authorizationInherited: "inherited run",
    authorizationUnknown: "Unknown",
    authorizationStatusPending: "Pending",
    authorizationStatusApproved: "Approved",
    authorizationStatusRejected: "Rejected",
    authorizationStatusCancelled: "Cancelled",
    authorizationStatusInterrupted: "Interrupted",
    authorizationActorJobApi: "approval API",
    authorizationActorJobCancel: "job cancel",
    authorizationActorResponderLost: "responder lost",
    authorizationOutcomeCompleted: "tool completed",
    authorizationOutcomeFailed: "tool failed",
    files: "Files",
    filesLoading: "Loading files…",
    artifacts: "Artifacts",
    artifactsLoading: "Loading artifacts…",
    artifactsNone: "No artifacts recorded.",
    artifactsRefresh: "Refresh artifacts",
    filesParent: "Open parent directory",
    diff: "Diff",
    diffLoading: "Loading diff…",
    diffNone: "No tool or Git changes recorded.",
    usageEvidence: "Message usage and context",
    compacted: "Compaction",
    historyIncluded: "{{included}} included / {{dropped}} dropped",
    emptyTitle: "No active run",
    emptyBody:
      "Send a message to start a turn. Plan, tools, and approvals will appear here.",
    working: "Working…",
    streaming: "Working. Tools and approvals update as the agent proceeds.",
    errorTitle: "Run interrupted",
    summaryTitle: "This run",
    statusQueued: "Queued",
    statusRunning: "Running",
    statusWaitingApproval: "Waiting for approval",
    statusCompleted: "Completed",
    statusFailed: "Failed",
    statusCanceled: "Canceled",
    model: "Model",
    duration: "Duration",
    startedAt: "Started",
    usage: "Usage",
    cost: "Cost",
    tokens: "{{count}} tokens",
    timeline: "Timeline",
    timelineStart: "Started your request",
    timelineTools: "Used {{count}} tools",
    timelineApproval: "Waiting for your approval",
    timelineComplete: "Run completed",
    timelineFailed: "Run failed",
    timelineCanceled: "Run canceled",
    filesTitle: "Files changed",
    filesNone: "No files were changed in this run.",
    planTitle: "Plan",
    planWaiting: "Waiting for plan…",
    planNone: "No plan for this run.",
    approvalsTitle: "Approvals",
    approvalsNone: "None pending.",
    approvalsWaiting: "Waiting",
    toolsTitle: "Tools",
    toolsNone: "No tool calls yet.",
    toolsWaiting: "Waiting for tool calls…",
    usageTitle: "Usage",
    prompt: "Prompt",
    completion: "Completion",
    cached: "Cached",
    total: "Total",
    sessionTotal: "Session total",
    contextEstimate: "Context estimate",
    compactedNotice:
      "Earlier conversation was compacted to free space.",
    restorePartial:
      "Some earlier messages could not be restored. The full record is saved locally.",
    usageUnavailable: "Usage unavailable",
    notLoaded: "Not loaded",
    notAvailable: "Not available",
  },
  commandPalette: {
    title: "Command palette",
    placeholder: "Search commands, workspaces, sessions and settings…",
    empty: "No matches.",
    groupActions: "Actions",
    groupWorkspaces: "Workspaces",
    groupSessions: "Sessions",
    groupSettings: "Settings",
    actionFocusComposer: "Focus the composer",
    actionNewSession: "New session",
    actionOpenSettings: "Open settings",
    actionToggleInspector: "Toggle the details panel",
    actionToggleTheme: "Toggle theme",
    unavailableNoWorkspace: "Open a workspace first.",
    unavailableNoSession: "Open a session first.",
    unavailableComposer: "The composer is not available right now.",
  },
  settings: {
    title: "Settings",
    lede: "Manage model access, approval preferences, and interface options. Everything is stored on this machine.",
    sectionGeneral: "General",
    sectionProviders: "Providers & Models",
    sectionTools: "Tools & Approvals",
    sectionWorkspace: "Workspace / Paths",
    sectionMemory: "Memory",
    sectionSessions: "Sessions",
    sectionKeyboard: "Keyboard shortcuts",
    sectionAdvanced: "Advanced",
    sectionAbout: "About",
    generalLede: "Appearance, language, and interface style.",
    advancedLede: "Diagnostics and migration entry points are no longer in the product UI.",
    advancedEmpty:
      "Use the `rove-bench` CLI for benchmarks. The workbench and diagnostics routes are development-only and unreachable in production builds.",
    general: {
      appearance: "Appearance",
      theme: "Theme",
      themeLight: "Light",
      themeDark: "Dark",
      language: "Language",
      languageDesc:
        "Interface language. Applies immediately and is stored on this machine.",
    },
    providers: {
      title: "Model providers",
      desc: "Choose where models come from. Keys stay in the system credential store and are never shown in plain text.",
      profile: "Profile",
      type: "Type",
      label: "Label",
      mode: "Mode",
      model: "Model",
      apiBase: "API base",
      apiKey: "API key",
      apiKeyEnv: "API key env name",
      apiKeyEnvHint:
        "When set, the key is read from this environment variable first. You rarely need to change it.",
      keyEnvAdvanced: "Key environment variable",
      defaultModel: "Default model",
      advanced: "Advanced",
      create: "New provider",
      edit: "Edit",
      editProfile: "Edit profile",
      delete: "Delete",
      use: "Use",
      test: "Test connection",
      listModels: "List models",
      save: "Save changes",
      cancel: "Cancel",
      changeKey: "Replace",
      keyHint:
        "The key is stored encrypted on this machine and never enters session records or logs.",
      localDemo: "Local demo",
      localDemoDesc: "Built-in model, no API key or network required",
      typeOpenai: "OpenAI",
      typeOpenaiResponses: "OpenAI Responses",
      typeAnthropic: "Anthropic",
      typeOllama: "Ollama",
      connected: "Connected — {{count}} models available",
      keyMissing: "Key is missing",
      unreachable: "Could not reach the provider",
      profileSummary: "{{label}} · {{apiBase}}",
      activeProfile: "Active profile",
      siliconflowQuick: "Add SiliconFlow DeepSeek V3.2",
      activeSelection: "Active selection",
      modeRuntimeDefault: "Runtime default",
      modeSavedProfile: "Saved profile",
      selectProfile: "Select profile…",
      savedProfiles: "Saved profiles",
      usingRuntimeDefault: "Using the API process default provider configuration.",
      labelField: "Label",
      typeField: "Type",
      modelField: "Model",
      editSecure: "Reconfigure secure profile",
      secureOnboarding: "Secure onboarding",
      catalogProfiles: "Shared catalog profiles",
      removeCatalogConfirm: "Remove this profile from the shared catalog?",
      listModelsAction: "List models",
    },
    runtime: {
      connection: "Connection",
      dataStorage: "Data storage",
      runtime: "Runtime",
      sessionRecovery: "Session recovery",
      theme: "Theme",
      workspace: "Workspace",
      status: "Status",
    },
    approval: {
      title: "Approval preferences",
      desc: "Choose which actions ask for your confirmation before running.",
      askMutations: "Ask before file changes and commands",
      askMutationsDesc: "Recommended. Reads stay unasked.",
      askAll: "Ask for every step",
      askAllDesc: "Most cautious; more prompts.",
    },
    export: {
      title: "Export conversation (redacted)",
      desc: "Export this session with sensitive values removed.",
      download: "Download",
    },
  },
  modelControl: {
    change: "Change session model settings",
    close: "Close model control",
    provider: "Session provider profile",
    model: "Session model",
    reasoning: "Session reasoning",
    maxSteps: "Session max steps",
    reloadModels: "Reload provider models",
    save: "Save session model",
    saving: "Saving…",
    loadingModels: "Loading provider models…",
    noModels: "Provider returned no models.",
    modelsNotLoaded: "Provider models not loaded",
    runtimeDefault: "Runtime default",
    runtimeProvider: "Runtime provider",
    providerDefault: "Provider default",
    updated: "Session model updated.",
    applyNote: "Changes apply from the next run in this session.",
    saveFailed:
      "The session model settings were not changed. Review the product error and retry.",
  },
  uiSkin: {
    label: "Interface style",
    desc: "Compare both visual directions before locking one in. Applies immediately on this machine.",
    warm: "Warm ivory",
    cool: "Cool steel",
  },
  migration: {
    importing: "Importing your workspace history",
    preparing: "Preparing your workspace history",
    importingBody:
      "Moving browser-saved workspaces and sessions into durable server storage.",
    preparingBody:
      "Checking saved browser data before reading the server catalog.",
    dismiss: "Dismiss import summary",
    imported: "Browser data imported ({{count}} records).",
    importedNoCount: "Browser data imported.",
    storageAuthoritative: "Server storage is now authoritative.",
    verifyTitle: "Import needs verification",
    verifyBody:
      "The server may already have accepted this import. Checking again will replay the exact saved request without duplicating browser data.",
    verifyAction: "Verify import",
    rejectedTitle: "Saved data was not accepted",
    rejectedBody:
      "The server rejected this browser snapshot. Its pending receipt was cleared, so a later retry will validate a fresh snapshot.",
    rejectedAction: "Retry import",
    receiptTitle: "Import receipt changed",
    receiptBody:
      "Another tab or a local storage change replaced the receipt while the server was applying this import.",
    checkAgain: "Check again",
    legacyRepairTitle: "Saved browser data needs repair",
    legacyRepairBody:
      "The saved workspace catalog could not be validated. Correct or clear the invalid browser entry before checking again.",
    receiptRepairTitle: "Import receipt needs repair",
    receiptRepairBody:
      "The saved import receipt is incomplete or invalid. Restore a valid receipt before checking again.",
    storageUnavailableTitle: "Browser storage is unavailable",
    storageUnavailableBody:
      "Rove could not safely persist or verify the import receipt. Allow this site to use browser storage, then check again.",
    lockUnavailableTitle: "Exclusive browser access is unavailable",
    lockUnavailableBody:
      "Rove needs a same-origin browser lock to prevent duplicate imports. Close other Rove tabs or use a browser that supports Web Locks, then check again.",
    unverifiedTitle: "Import could not be verified",
    unverifiedBody:
      "Rove could not establish a trusted server acknowledgement for the saved browser data.",
    assurance:
      "Rove has not deleted your browser-saved workspaces, sessions, or provider references, and will not replace them with an empty server catalog.",
  },
  codeCopy: {
    copy: "Copy code",
    copied: "Copied",
    failed: "Copy failed",
  },
  diff: {
    fallback: "Diff could not be parsed",
    unstructured: "Unstructured diff output",
    canonical: "Workspace change",
    markdown: "Markdown diff",
  },
  errors: {
    bootTitle: "Could not start",
    bootBody: "The product shell failed to finish loading.",
    routeTitle: "Cannot open this session",
    routeBody: "The session route is invalid or no longer exists.",
    code: "code: {{code}}",
  },
  boot: {
    loading: "Starting the product shell…",
    checking: "Connecting to the local service…",
  },
  empty: {
    title: "Open a workspace to start",
    body: "rove runs agent turns against a real local root. Open a folder or repo path, then chat in a session.",
    absolutePath: "Absolute path",
    kind: "Kind",
    folder: "Folder",
    repo: "Repo",
    open: "Open workspace",
    browse: "Browse…",
    browseFolder: "Open folder",
    browseFolderHint:
      "Opens the system folder picker. You can also paste an absolute path below.",
    pickerUnavailable:
      "Native folder picker is unavailable. Enter an absolute path instead.",
    configureProvider: "Configure provider",
    recents: "Recents",
    pathRequired: "Enter an absolute path to open.",
  },
  workspace: {
    label: "Workspace",
    newSession: "New session",
    sessions: "Sessions",
    pin: "Pin",
    unpin: "Unpin",
    remove: "Remove",
    add: "Add workspace",
    close: "Close workspaces",
    search: "Search workspaces and sessions",
    searchPlaceholder: "Search names",
    searchScope: "Loaded workspace and session names only",
    noMatches: "No loaded workspace or session names match.",
    expandProject: "Expand {{name}} sessions",
    collapseProject: "Collapse {{name}} sessions",
    projectActions: "Actions for {{name}}",
    newSessionIn: "New session in {{name}}",
    openDescription: "Open an absolute local folder or repository path. No full-disk scan.",
    running: "Running",
    runningCount: "{{count}} running",
    needsAttention: "Needs attention",
    forked: "Forked session",
    forkedRemovedParent: "Forked session, parent removed",
    parentRemoved: "Parent removed",
    forkPrefix: "Fork",
    sessionsAndBranches: "Sessions and branches",
    pinWorkspace: "Pin workspace",
    unpinWorkspace: "Unpin workspace",
    removeWorkspace: "Remove workspace from list",
    removeWorkspaceArmed: "Confirm removal and its sessions",
    settings: "Settings",
    pathRules: "Path rules",
    pathRulesBody:
      "Add workspaces from the sidebar using an absolute local path. Folder roots expose that directory; Repo roots identify a checkout. Removing an entry removes its sessions but never deletes files from disk.",
    known: "Known workspaces",
    none: "No workspaces are registered yet. Add an absolute Folder or Repo path from the sidebar.",
    removeConfirm:
      "Remove this workspace and its sessions from the catalog? Local files are not deleted.",
    active: " (active)",
    pinned: "Pinned",
    opened: "Opened {{time}}",
    sessionsTitle: "Sessions",
    noSessions: "No sessions",
    noSessionsBody: "No sessions in this workspace.",
    sessionName: "Session name",
    openPickerFailed: "Failed to open the folder picker.",
  },
  tools: {
    lede: "Default tool authorization and execution limits.",
    approvalTitle: "Default approval policy",
    ask: "Ask",
    auto: "Auto",
    never: "Never",
    askDesc: "Pause when a tool requires approval.",
    autoDesc: "Allow runtime-approved tool execution.",
    neverDesc: "Reject tool calls that require approval.",
    maxStepsTitle: "New-session execution limit",
    maxStepsLabel: "Default maximum steps for new sessions",
    saveDefault: "Save default",
  },
  keyboard: {
    lede: "Fast paths for the primary session and navigation actions.",
    title: "Application shortcuts",
    focusComposer: "Focus message composer",
    focusComposerDesc: "Move keyboard focus to the message composer.",
    newSession: "New session",
    newSessionDesc: "Create a session in the active workspace.",
    openSettings: "Open settings",
    openSettingsDesc: "Open General settings from the product shell.",
    toggleInspector: "Toggle run inspector",
    toggleInspectorDesc: "Show or hide the current run inspector.",
    openCommandPalette: "Command palette",
    openCommandPaletteDesc: "Search commands, workspaces, sessions and settings.",
  },
  about: {
    lede: "Live API, product storage, and session recovery health.",
    apiProxy: "API proxy",
    host: "Host",
    apiVersion: "API version",
    runtimeConnection: "Runtime connection",
    adapter: "Adapter",
    workspaceKind: "Workspace kind",
    workspaceIdentity: "Workspace identity",
    filesystemRead: "Filesystem read",
    filesystemWrite: "Filesystem write",
    processRun: "Process run",
    processStdio: "Process stdio",
    processBackground: "Background process",
    processPty: "Pseudo-terminal",
    observations: "Observations",
    available: "Available",
    unavailable: "Unavailable",
    authorized: "Authorized",
    restricted: "Restricted",
    enabled: "Enabled",
    disabled: "Disabled",
    allowed: "Allowed",
    diagnosticOnly: "Diagnostic only",
    selector: "Agent selector",
    workspaceSource: "Workspace source",
    workspaceInstructions: "Workspace instructions",
    remediationProcedures: "Remediation procedures",
    procedureLimit: "Procedure limit",
    resumeStatus: "Recovery status",
    resumeWorkspaces: "Workspaces",
    resumeSessions: "Sessions",
    resumeBound: "Bound sessions",
    resumeRunning: "Running sessions",
    resumeAttention: "Sessions needing attention",
    refreshing: "Refreshing runtime health…",
    storeUnavailable:
      "Data storage is unavailable. Workspace, session, and resume health cannot be read.",
    refresh: "Refresh runtime",
    loading: "Loading runtime health…",
    unavailableTitle: "Runtime information unavailable",
  },
  memory: {
    editTopic: "Edit topic",
    searchPlaceholder: "Title, slug, or description",
    allTypes: "All types",
    allScopes: "All scopes",
    allSources: "All sources",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    refreshTopic: "Refresh topic",
    createTopic: "Create topic",
    count: "{{count}} topics",
    metadata: "Memory topic metadata",
    contentLabel: "Memory topic content",
    listLabel: "Durable memory topics",
    layer: "Storage",
    durable: "Durable",
    created: "Created",
    updated: "Updated",
    notRecorded: "Not recorded",
    noDescription: "No description recorded.",
    metadataTruncated: "Some topic metadata could not be displayed.",
    contentTruncated: "Topic content is incomplete. Editing is disabled to prevent content loss.",
    loadingContent: "Loading topic content…",
    deleteConfirm: "Delete “{{title}}”?",
    deleteWarning: "This permanently removes the topic. This action cannot be undone.",
    confirmDelete: "Confirm delete",
    deleting: "Deleting…",
    listFailed: "Memory topics could not be loaded. Please retry.",
    detailFailed: "The topic could not be loaded. Refresh and retry.",
    deleteFailed: "The topic could not be deleted. Please retry.",
    saveFailed: "The topic was not saved and may have changed. Keep your draft and refresh the topic before retrying.",
    lastLoaded: "Showing the last loaded topics.",
    summary: "{{type}} · {{scope}} · {{confidence}}% confidence",
    type_user: "User",
    type_feedback: "Feedback",
    type_project: "Project",
    type_reference: "Reference",
    scope_global: "Global",
    scope_project: "Project",
    scope_session: "Session",
    source_product_settings: "Settings",
    source_llm_tool: "Agent tool",
    source_other: "Other",
    source_unknown: "Unknown",
    title: "Memory",
    needWorkspace: "Select a workspace to inspect its durable memory.",
    find: "Find topics",
    search: "Search",
    clear: "Clear",
    open: "Open",
    selected: "Selected",
    noMatch: "No durable memory topics match these filters.",
    empty: "No durable memory topics are available.",
    type: "Type",
    scope: "Durable scope",
    source: "Source",
    all: "All",
    slug: "Slug",
    topicTitle: "Title",
    confidence: "Confidence",
    description: "Description",
    content: "Content",
    durableTopics: "Durable topics",
    emptyBody: "No stored body content.",
    newTopic: "New durable topic",
    editTopicTitle: "Edit durable topic",
    deleteTopic: "Delete topic",
    saveTopic: "Save changes",
    testServer: "Test",
    testing: "Testing…",
    loading: "Loading durable memory topics…",
    scopeLabel: "Durable scope",
  },
  mcp: {
    title: "MCP servers",
    addServer: "Add server",
    addServerTitle: "Add MCP server",
    editServerTitle: "Edit {{name}}",
    serverName: "Server name",
    timeout: "Connection timeout (ms)",
    enabled: "Enabled",
    required: "Required at startup",
    command: "Command",
    args: "Arguments (one per line)",
    envNames: "Environment names (one per line)",
    workspaceServers: "Workspace servers",
    loading: "Loading MCP servers…",
    none: "No MCP servers in this workspace.",
    removeConfirm: "Remove {{name}} from this workspace?",
    remove: "Remove",
  },
  trust: {
    title: "Project trust",
    capabilities: "Capabilities",
    changed: "Changed",
    granted: "Granted",
  },
  richText: {
    linkOpenUnsupported: "The current host cannot open external links.",
    linkOpenBlocked: "Blocked that link: only http and https links are allowed.",
    linkOpenFailed: "The system could not open that link.",
  },
};

export default enUS;

