import type { CopyDictionary } from "./zh-CN";

const enUS: CopyDictionary = {
  desktopProviders: {
    description: "Desktop keeps keys in Windows Credential Manager. Saved provider settings do not contain plain-text keys.",
    defaultSelection: "Using the default model provider settings.",
    onboardingHint: "Continue to enter your key in a secure system window. Settings are saved only after the connection test succeeds.",
    preset: "Use SiliconFlow preset",
    compatible: "OpenAI-compatible",
    credentialHint: "Windows collects the key in a secure window, outside web forms and browser storage.",
    verifying: "Verifying…",
    saveVerify: "Save & verify",
    verified: "Verified and saved {{label}}. Now using {{model}}.",
    connected: "Connected to {{label}}. The model list is available.",
    modelsLoaded: "Loaded {{count}} models for {{label}}.",
    selected: "Selected {{label}} · {{model}}.",
    removed: "Model provider settings removed.",
    probeSummary: "Connection test: {{count}} models available · Incremental replies: {{streaming}} · Tool use: {{tools}} · Usage tracking: {{usage}}",
    supported: "Supported",
    unsupported: "Not supported",
    models: "Available models: {{models}}",
    empty: "No model providers configured. Add one above to get started.",
    active: " (active)",
    noDefaultModel: "No default model",
    selecting: "Selecting…",
    reconfigure: "Reconfigure",
    remove: "Remove",
    credentialKeyring: "Key saved in system storage",
    credentialEnv: "Key from environment variable",
    credentialFile: "Key from local file",
    credentialNone: "No key configured",
  },
  artifactLabels: {
    report: "Run report",
    task_state: "Task progress",
    trace: "Activity log",
    registered: "Run-generated file",
    tool_artifact: "Tool-generated file",
    available: "Available",
    cleaned: "Content removed",
    invalid: "Content could not be verified",
    too_large: "Large file — download to view",
  },
  review: {
    title: "Read-only Review",
    refresh: "Refresh Reviews",
    cancel: "Cancel Review",
    loading: "Loading Reviews…",
    empty: "No Review runs",
    emptyBody: "Start a Review from the composer to inspect a Git target without changing it.",
    run: "Review run",
    target: "Target",
    files: "Files",
    findings: "Findings",
    unchecked: "Unchecked",
    warnings: "Warnings",
    passBody: "No actionable findings were reported.",
    loadingFindings: "Loading findings…",
    unavailableFindings: "Finding details are unavailable.",
    openFiles: "Open in Files",
    more: "Load more findings",
    partialBody: "Some portions were not checked. Review the coverage before acting.",
    staleBody: "The target changed or needs attention. Start a new Review for the current files.",
    unavailableBody: "The Review target or service is unavailable.",
    cancelledBody: "Review was cancelled before completion.",
    errorBody: "Review failed. No chat turn was changed.",
    error: "The Review action could not be completed. Refresh and retry.",
    warningBody: "This Review has warnings. Check its coverage before relying on the results.",
    unknown: "Unknown",
    status_queued: "Queued",
    status_running: "Running",
    status_pass: "Passed",
    status_findings: "Findings",
    status_partial: "Partial",
    status_stale: "Target changed",
    status_needs_attention: "Needs attention",
    status_unavailable: "Unavailable",
    status_cancelled: "Cancelled",
    status_error: "Failed",
  },
  chrome: {
    brandName: "rove",
    brandTag: "local agent",
    loadError: "The action could not be completed. Refresh and retry.",
    partial: "Some records could not be loaded.",
    download: "Download {{name}}",
    previewUnavailable: "Preview is unavailable for this type.",
    previewHtmlOpen: "Open in isolated preview",
    previewHtmlClose: "Close isolated preview",
    previewHtmlHint: "HTML can execute in an isolated origin; the preview page cannot read product credentials.",
    previewHtmlActive: "Isolated preview session is open; its token is revoked on close.",
    invalidContent: "This content cannot be previewed safely.",
    cleaned: "Artifact data has been cleaned.",
    format: "Format",
    offlineHtml: "Offline HTML",
    refreshDiff: "Refresh diff",
    noPatch: "No patch was recorded.",
    binary: "Binary file",
    truncated: "Partial content",
    fullPatch: "Full patch",
    summaryOnly: "Summary only",
    directory: "Folder",
    loadMore: "Load more",
    scanLimited: "This directory is large; only results within the safety limit are shown.",
    advanced: "Advanced",
    cancelEdit: "Cancel edit",
    models: "Available models ({{count}})",
    removeProvider: "Remove this provider profile? Sessions will not be deleted.",
    settingsError: "The settings action could not be completed. Check the current settings and retry.",
    providerError: "The provider action could not be completed. Check the connection and settings, then retry.",
  },
  common: {
    retry: "Retry",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    close: "Close",
    back: "Back",
    loading: "Loading…",
    none: "None",
    noSavedProfiles: "No saved profiles yet.",
    more: "More",
    actions: "Actions",
    dismiss: "Got it",
    copy: "Copy",
    copied: "Copied",
  },
  connection: {
    ok: "API connected",
    error: "API unreachable",
    checking: "Checking API…",
  },
  theme: {
    toLight: "Switch to light theme",
    toDark: "Switch to dark theme",
  },
  locale: {
    label: "Language",
    zhCN: "中文",
    enUS: "English",
  },
  nav: {
    settings: "Settings",
    backToChat: "Back to chat",
    workspace: "Workspace",
    expandWorkspace: "Expand workspace list",
    collapseWorkspace: "Collapse workspace list",
    inspector: "Details",
    expandInspector: "Expand details",
    collapseInspector: "Collapse details",
    closeInspector: "Close details",
    newSession: "New session",
    newTask: "New task",
    search: "Search",
    searchWorkspace: "Search sessions",
  },
  chat: {
    responding: "Responding…",
    aborted: "(aborted)",
    assistant: "Assistant",
    you: "You",
    send: "Send",
    sendUnexpectedError: "Could not confirm the send. Your draft is preserved; check the conversation before trying again.",
    sendWhileRunningHint: "Send while running (Alt+Enter interjects)",
    sendKeyHintEnter: "Enter to send",
    sendKeyHintModEnter: "Ctrl+Enter to send",
    sendKeyHintShiftEnter: "Shift+Enter for a new line",
    sendKeyHintPlainEnter: "Enter for a new line",
    sendKeyHintAltEnter: "Alt+Enter to interject",
    queueTitle: "Queued messages",
    todoDockLabel: "Run plan",
    todoDockProgress: "{{done}}/{{total}} done",
    todoDockAllDone: "All steps done",
    stop: "Stop",
    placeholder: "Type a message",
    loadOlder: "Load {{n}} earlier turns",
    loadOlderHistory: "Load older history",
    loadingOlderHistory: "Loading older history…",
    retryOlderHistory: "Try again",
    restoring: "Restoring this conversation…",
    transcriptLabel: "Conversation",
    restorePartialTitle: "Partial conversation history",
    restorePartial:
      "Some earlier messages could not be restored. New messages are unaffected.",
    restoreFailed: "Conversation restore failed",
    restoreError: "No empty history has been substituted for the failed read.",
    restoreRetry: "Retry restore",
    startNewSession: "Start a new session",
    emptyTranscript: "Send a message to start a run in this session.",
    approve: "Approve",
    reject: "Reject",
    onlyThisTime: "Only this time",
    queue: "Queue",
    revoke: "Revoke",
    promote: "Send now",
    disabledRestoring: "Finishing restoring this conversation…",
    sendQueuedRestoring: "Sending as soon as the transcript is back…",
    disabledSettings: "Session settings are loading…",
    disabledRestoreError: "Retry transcript restore before sending.",
    disabledRoute: "Resolve the product route before sending.",
    model: "Model",
    mode: "Mode",
    turn: "Turn {{n}}",
    currentTurn: "Current turn",
    inputSubmitted: "Input submitted",
    inputClosed: "Input closed",
    revokeTitle: "Revoke message",
    returnToLatest: "Return to latest",
    minimapLabel: "Conversation navigation",
    minimapMarker: "Marker {{n}} of {{total}}: {{role}}",
    deliveryThisTurn: "This turn",
    deliveryNextTurn: "Next turn",
    statusJoiningTurn: "Waiting to join this turn",
    statusJoinedTurn: "Joined this turn",
    statusNextTurn: "Starts next turn",
    evidence: "Message usage and context",
    reviewUncommitted: "Uncommitted changes",
    reviewBase: "Base revision",
    reviewCommit: "Commit",
    activitySummary: "Tool calls × {{n}}",
    activityBlocking: "{{n}} awaiting interaction",
    activityElapsed: "Running {{n}}s",
    activityElapsedFrozen: "About {{n}}s",
    toolDuration: "Duration",
    diffTruncated: "Diff truncated.",
    outputTruncated: "Output truncated.",
    matchesTruncated: "Matches truncated.",
    filesTitle: "Files",
    matchesTitle: "Matches",
    chipReadOnly: "read only",
    chipMutation: "mutation capable",
    chipHighRisk: "high risk",
    chipWorkspaceChanged: "workspace changed",
    phaseSending: "Sending…",
    phaseWaitingModel: "Waiting for the model…",
    phaseCompacting: "Compacting context…",
    phaseCompactingDegraded: "Context compaction degraded, continuing…",
    phaseTool: "Running {{name}}…",
    phasePlanning: "Planning the next step…",
    phaseFinalizing: "Finalizing…",
    phaseDegraded: "Execution degraded: {{summary}}",
    statusElapsed: "{{n}}s",
    working: "Working…",
    compactionDivider: "Context compacted",
    compactionDividerAuto: "Context compacted automatically",
    receiptActions: "{{n}} actions",
    receiptAction: "1 action",
    receiptTokens: "{{n}} tokens",
    toolStateRunning: "running",
    toolStateDone: "done",
    toolStateError: "failed",
    toolStateWaiting: "waiting",
    toolCopy: "Copy tool payload",
    usageLabel: "Context usage",
    usageAriaUsed: "Context using {{used}} tokens of {{total}}",
    usageAriaNoWindow: "Context using {{used}} tokens (model did not report a window)",
    usageModeUsed: "{{n}} used",
    usageModeRemaining: "{{n}} left",
    usageCache: "Cache hit {{percent}}%",
    smartStopRestored: "Stopped. Your message is back in the composer.",
    smartStopRestoredSnapshot:
      "Stopped. The draft as you sent it, pasted content included, is back in the composer.",
    smartStopPartialAbort:
      "Stopped. This turn had already produced output, so it stays in the conversation.",
    smartStopRevokeFailed: "Could not revoke the message. The draft is back in the composer.",
    queuedEdit: "Edit",
    queuedMoveUp: "Move up one",
    queuedMoveDown: "Move down one",
    queuedMoveFailed: "The move failed. The content is back in the composer.",
    queuedEditing: "Editing — submitting replaces this message",
    promoteSuccessor: "Send now (after this turn)",
    promoteSuccessorHint:
      "Does not interrupt the current turn; it is dispatched as the next turn once this one reaches its terminal boundary.",
    interject: "Interject (interrupt)",
    interjectHint: "Injects into the current turn; it interrupts the step the model is running.",
    promoteFailed: "Send-now did not run: the current turn may already have ended.",
    interjectFailed: "The interjection did not run: the current turn may already have ended.",
    queueMoveFailed: "The move failed: the queue may have changed. Try again.",
    queueMoveRejected:
      "The queue had changed, so nothing moved; the server's order is shown instead.",
    queueReorderUnavailable: "Only queued successor messages can be reordered.",
    retryStranded: "Retry this message",
    retryStrandedHint:
      "The server could not start this queued message. Retrying asks it to try again; nothing is queued until it answers.",
    retryStrandedBusy: "Retrying…",
    retryStrandedAccepted: "Retry accepted — the server queued this message again.",
    retryStrandedStarting: "Retry accepted — the server is starting this message.",
    retryStrandedFailed: "Retry failed: {{reason}}",
    compactAction: "Compact context now",
    compactBusy: "Compacting the context…",
    compactIdleOnly: "Manual compaction is available while the session is idle.",
    compactNoop:
      "This call produced no new summary: the context may already be compacted, or there may be nothing to compact.",
    compactNoopCircuit:
      "Nothing to compact; the summary model has already failed {{count}} consecutive times.",
    compactDone: "The context was compacted.",
    compactMode: "Compaction mode: {{mode}}",
    compactModeNone: "None",
    compactModeDeterministic: "Deterministic summary",
    compactModeModelGenerated: "Model summary",
    compactModeAutomatic: "Automatic summary",
    compactModeDegraded: "Degraded summary",
    compactModeDisabled: "Disabled",
    compactDegraded:
      "This compaction was degraded: the model summary failed ({{code}}), so the stored summary is the deterministic fallback.",
    compactDegradedNoCode:
      "This compaction was degraded: the stored summary is the deterministic fallback.",
    compactCircuit:
      "The summary model has failed {{count}} consecutive times; automatic compaction is refused, while a manual run still spends one probe.",
    compactCircuitUntil: "Automatic compaction is refused until {{until}}.",
    compactSummaryLabel: "Summary excerpt",
    compactSummaryTruncated:
      "Only the beginning of the summary is shown; this is not the whole summary.",
    compactTokens: "Estimated context after compaction: {{tokens}} tokens",
    compactSourceMessages: "Messages in this compaction: {{count}}",
    compactActive:
      "The session is still running, so nothing was compacted. Try again once this turn ends.",
    compactFailed: "Compaction did not finish: {{error}}",
    compactNoRun: "This session has no run yet, so there is nothing to compact.",
    retry: "Retry",
    editMessage: "Edit",
    forkSession: "Copy session",
    triggerCommands: "Commands",
    triggerFiles: "Workspace files",
    triggerFilesLimited: "Showing the first {{n}}. Type more to narrow the list.",
    triggerNoFiles: "No matching files",
    messageCopy: "Copy",
    messageCopied: "Copied",
    pasteChip: "Pasted content ({{count}} characters)",
    smartStopRestoredPastes: "Restored {{n}} pasted attachment(s) from before that send.",
    pasteExpand: "View full text",
    pasteRejectedTooMany: "At most {{n}} pasted attachments per draft. This one was not accepted.",
    pasteRejectedTooLarge: "Pasted attachments exceed the {{n}} KB cap. This one was not accepted.",
    attachFile: "Attach files",
    attachFileHint: "png, jpg, jpeg, webp, gif, pdf, txt, or md; up to 20 MiB each, 16 MiB for images.",
    attachmentDropHint: "Drop to attach",
    attachmentUploading: "Uploading…",
    attachmentRetrying: "Upload failed; retrying…",
    attachmentUploaded: "Ready",
    attachmentRestored: "Restored, waiting for the server",
    attachmentRemove: "Remove attachment {{name}}",
    attachmentFailureTooLarge: "{{name}} is over the {{limit}} cap and was not added.",
    attachmentFailureUnsupported: "{{name}} is not a supported attachment type.",
    attachmentFailureTooMany: "At most {{n}} attachments per message.",
    attachmentFailureQuota: "This session's attachment quota is full.",
    attachmentFailureBusy: "The attachment service is busy; try again shortly.",
    attachmentFailureTimeout: "The upload timed out and was not added.",
    attachmentFailureUnavailable: "Attachment storage is unavailable right now.",
    attachmentFailureInvalid: "The server refused this attachment.",
    attachmentFailureExpired: "{{name}} has expired; add it again.",
    attachmentFailureMissing: "{{name}} can no longer be read; add it again.",
    attachmentFailureNetwork: "{{name}} did not reach the server.",
    attachmentFailureUnexpected: "{{name}} could not be uploaded.",
    attachmentWarningSecretName: "The file name looks like a credential; it was stored as given.",
    attachmentWarningSecretContent: "The content looks like it holds a credential; it was stored as given.",
    attachmentWarningTypeMismatch: "The declared type did not match the bytes; the verified type was stored.",
    attachmentWarningOther: "The server returned an unrecognised warning.",
    attachmentLink: "{{name}} · {{size}}",
    attachmentShowImage: "Show image {{name}}",
    attachmentHideImage: "Hide image {{name}}",
    attachmentSave: "Save attachment {{name}}",
    attachmentLoadFailed: "The attachment could not be read.",
    attachmentDegraded: "This image was not sent to the model",
    attachmentAvailabilityMissing: "The attachment content is missing",
    attachmentAvailabilityCorrupt: "The attachment content is corrupt",
    attachmentAvailabilityExpired: "The attachment has expired",
    readingWidth: "Reading width (Left/Right arrows, double-click to reset)",
    readingWidthValue: "Reading width {{width}} pixels",
  },
  inspector: {
    title: "Details",
    tabsLabel: "Details tabs",
    tabNew: "New tab",
    tabPending: "Pending",
    tabStatus: "Run",
    tabFiles: "Files",
    tabChanges: "Changes",
    tabReview: "Review",
    tabFile: "File",
    tabSubagents: "Subagents",
    openTab: "Open a tab",
    closeTab: "Close {{name}}",
    launcherTitle: "Open a tab",
    noTabs: "No tabs are open. Use + to open one.",
    noTabsTitle: "No tabs open",
    maximize: "Maximize panel",
    unmaximize: "Restore panel",
    approvalsNoneBody: "Tool approvals the run requests will appear here.",
    subagentsNone: "No subagent runs",
    subagentsNoneBody:
      "Subagent transcripts will appear here when a run delegates work.",
    filesBreadcrumbs: "File path",
    filesRoot: "workspace",
    filesEmpty: "No files here",
    filesEmptyBody: "This directory is empty, or nothing was listed.",
    filesNoWorkspace: "Open a workspace session to browse its files.",
    fileUnavailable: "File unavailable",
    fileUnavailableBody: "The file could not be loaded from this workspace.",
    filePreviewUnavailableBody:
      "Use download or open externally to inspect it.",
    fileLineCap: "showing first {{shown}} of {{total}} lines",
    fileOpenExternal: "Open externally",
    fileSource: "View source",
    fileRendered: "View rendered",
    diffSummary: "{{count}} changes +{{additions}} −{{deletions}}",
    diffNoneBody:
      "Changes the run or Git recorded will appear here.",
    approvalDetail: "Approval details",
    approvalSubmitting: "Submitting decision; awaiting server state…",
    approvalUnavailable: "This request is no longer pending in the current run. This does not confirm approval by this window or tool success.",
    panelWidth: "Panel width (Left/Right arrows, Home/End)",
    panelWidthValue: "Panel width {{width}} pixels",
    approvalScope: "Only the requested tool call. No permanent permission is granted.",
    sidebarWidth: "Navigation width (Left/Right arrows, Home/End)",
    sidebarWidthValue: "Navigation width {{width}} pixels",
    authorizationTitle: "This session's authorization requests",
    authorizationLoading: "Loading this session's authorization requests…",
    authorizationError: "Could not load this session's authorization requests.",
    authorizationNone: "No tool authorization requests were recorded for this session.",
    authorizationPartial: "The page was truncated; only the most recent authorization requests are shown.",
    authorizationHistoryNote:
      "Decision status and channel come from the durable record; fields that were never recorded read as unknown. A successful tool result does not mean this window approved it.",
    authorizationHistoryUnavailable:
      "The decision actor and time are not persisted yet, so they read as unknown; a successful tool result does not mean this window approved it.",
    authorizationColumnTool: "Tool",
    authorizationColumnCall: "Call ID",
    authorizationColumnScope: "Scope",
    authorizationColumnDecision: "Decision",
    authorizationColumnActor: "Decision channel",
    authorizationColumnTime: "Time",
    authorizationColumnOutcome: "Outcome",
    authorizationRun: "run {{ordinal}}",
    authorizationRunLabel: "linked run",
    authorizationInherited: "inherited run",
    authorizationUnknown: "Unknown",
    authorizationStatusPending: "Pending",
    authorizationStatusApproved: "Approved",
    authorizationStatusRejected: "Rejected",
    authorizationStatusCancelled: "Cancelled",
    authorizationStatusInterrupted: "Interrupted",
    authorizationActorJobApi: "approval API",
    authorizationActorJobCancel: "job cancel",
    authorizationActorResponderLost: "responder lost",
    authorizationOutcomeCompleted: "tool completed",
    authorizationOutcomeFailed: "tool failed",
    files: "Files",
    filesLoading: "Loading files…",
    artifacts: "Artifacts",
    artifactsLoading: "Loading artifacts…",
    artifactsNone: "No artifacts recorded.",
    artifactsRefresh: "Refresh artifacts",
    filesParent: "Open parent directory",
    diff: "Diff",
    diffLoading: "Loading diff…",
    diffNone: "No tool or Git changes recorded.",
    usageEvidence: "Message usage and context",
    compacted: "Compaction",
    historyIncluded: "{{included}} included / {{dropped}} dropped",
    emptyTitle: "No active run",
    emptyBody:
      "Send a message to start a turn. Plan, tools, and approvals will appear here.",
    working: "Working…",
    streaming: "Working. Tools and approvals update as the agent proceeds.",
    errorTitle: "Run interrupted",
    summaryTitle: "This run",
    statusQueued: "Queued",
    statusRunning: "Running",
    statusWaitingApproval: "Waiting for approval",
    statusCompleted: "Completed",
    statusFailed: "Failed",
    statusCanceled: "Canceled",
    model: "Model",
    duration: "Duration",
    startedAt: "Started",
    usage: "Usage",
    cost: "Cost",
    tokens: "{{count}} tokens",
    timeline: "Timeline",
    timelineStart: "Started your request",
    timelineTools: "Used {{count}} tools",
    timelineApproval: "Waiting for your approval",
    timelineComplete: "Run completed",
    timelineFailed: "Run failed",
    timelineCanceled: "Run canceled",
    filesTitle: "Files changed",
    filesNone: "No files were changed in this run.",
    planTitle: "Plan",
    planWaiting: "Waiting for plan…",
    planNone: "No plan for this run.",
    approvalsTitle: "Approvals",
    approvalsNone: "None pending.",
    approvalsWaiting: "Waiting",
    toolsTitle: "Tools",
    toolsNone: "No tool calls yet.",
    toolsWaiting: "Waiting for tool calls…",
    usageTitle: "Usage",
    prompt: "Prompt",
    completion: "Completion",
    cached: "Cached",
    total: "Total",
    sessionTotal: "Session total",
    contextEstimate: "Context estimate",
    prunedTools: "Pruned tool results",
    prunedToolsValue: "{{count}} · {{size}} not sent",
    prunedOmitted: "Messages left out whole",
    prunedOmittedValue: "{{count}} · {{size}}",
    pruningPolicy: "Pruning rule",
    pruningPolicyUnknown: "an unknown rule",
    pruningScope: "Scope",
    pruningScopeValue: "This compaction request only; the conversation is unchanged",
    pruningDigests: "Result identities",
    pruningDigestsValue: "{{count}} (newest first)",
    compactedNotice:
      "Earlier conversation was compacted to free space.",
    restorePartial:
      "Some earlier messages could not be restored. The full record is saved locally.",
    usageUnavailable: "Usage unavailable",
    notLoaded: "Not loaded",
    notAvailable: "Not available",
  },
  commandPalette: {
    title: "Command palette",
    placeholder: "Search commands, workspaces, sessions and settings…",
    empty: "No matches.",
    groupActions: "Actions",
    groupWorkspaces: "Workspaces",
    groupSessions: "Sessions",
    groupSearch: "This session's messages",
    groupSettings: "Settings",
    actionFocusComposer: "Focus the composer",
    actionNewSession: "New session",
    actionOpenSettings: "Open settings",
    actionToggleInspector: "Toggle the details panel",
    actionToggleTheme: "Toggle theme",
    actionSearchSessionMessages: "Search this session's messages",
    actionSearchAll: "Search sessions and event records",
    searchLoading: "Searching this session's messages…",
    searchEmpty: "No matching message in this session.",
    searchError: "This session's message search failed: {{error}}",
    searchUnavailable: "Open a session first.",
    searchTooShort: "Searching this session's messages needs at least 1 character.",
    searchInvalidInput:
      "The term contains control characters the search cannot carry; remove them and try again.",
    unavailableNoWorkspace: "Open a workspace first.",
    unavailableNoSession: "Open a session first.",
    unavailableComposer: "The composer is not available right now.",
  },
  search: {
    title: "Search across corpora",
    lede: "Find a term in session messages and in run event records (trace). Results are bounded excerpts and may not be all the matches.",
    placeholder: "Type a term…",
    scopeLabel: "Search scope",
    scopeSession: "This session's messages",
    scopeWorkspace: "Workspace session messages",
    scopeTrace: "This session's event records",
    submit: "Search",
    close: "Close search",
    loading: "Searching…",
    empty: "No matches.",
    emptyTrace: "No match in these runs' event records.",
    emptyWorkspace: "No matching session message in this workspace.",
    partialBudget:
      "This pass read only part of the event records, so these are not all the matches; you can load the next page.",
    loadingMore: "Loading more…",
    loadMore: "Load more",
    exhausted: "Last page reached.",
    expired:
      "The run the cursor pointed at is no longer in the session (its event records may have been cleaned), so the cursor was dropped and the search restarted from the first page.",
    shortTermWorkspace:
      "The workspace scope needs at least 3 characters; use the session scope instead.",
    tooLong: "The term may be at most 128 bytes.",
    blank: "Type a term first.",
    error: "Search failed: {{error}}",
    unknownError: "The server gave no reason.",
    scopeMismatch:
      "The server answered for a different scope, so this result was ignored.",
    sessionUnknown: "Unknown session ({{id}})",
    hitMessage: "Message",
    hitTrace: "Event record",
    traceRun: "run {{ordinal}}",
    traceNoRun: "run unknown",
    noTime: "No timestamp",
    openSession: "Open session",
    locateMessage: "Locate this message",
    located: "Located that message.",
    notLoaded: "That message is outside the loaded records, so it cannot be located.",
    idle: "Type a term to start searching.",
    scopeSessionUnavailable: "The session scope needs an open session.",
    scopeWorkspaceUnavailable: "The workspace scope needs an open workspace.",
    scopeTraceUnavailable: "The event-record scope needs an open session.",
    sessionHits: "{{count}} hits",
  },
  settings: {
    title: "Settings",
    lede: "Manage model access, approval preferences, and interface options. Everything is stored on this machine.",
    sectionGeneral: "General",
    sectionProviders: "Providers & Models",
    sectionTools: "Tools & Approvals",
    sectionWorkspace: "Workspace / Paths",
    sectionMemory: "Memory",
    sectionSessions: "Sessions",
    sectionKeyboard: "Keyboard shortcuts",
    sectionAdvanced: "Advanced",
    sectionAbout: "About",
    generalLede: "Appearance, language, and interface style.",
    advancedLede: "Diagnostics and migration entry points are no longer in the product UI.",
    advancedEmpty:
      "Use the `rove-bench` CLI for benchmarks. The workbench and diagnostics routes are development-only and unreachable in production builds.",
    general: {
      appearance: "Appearance",
      theme: "Theme",
      themeLight: "Light",
      themeDark: "Dark",
      language: "Language",
      languageDesc:
        "Interface language. Applies immediately and is stored on this machine.",
      fontScale: "Font size",
      fontScaleDesc: "Adjust the text size of the conversation reading area. Stored on this machine.",
      fontScaleSmaller: "Smaller text",
      fontScaleLarger: "Larger text",
      fontScaleReset: "Reset font size",
    },
    providers: {
      title: "Model providers",
      desc: "Choose where models come from. Keys stay in the system credential store and are never shown in plain text.",
      profile: "Profile",
      type: "Type",
      label: "Label",
      mode: "Mode",
      model: "Model",
      apiBase: "API base",
      apiKey: "API key",
      apiKeyHint:
        "Sent once to the local Rove API and stored in the OS credential store; it is never shown or saved in this app.",
      apiKeyRemoteHint:
        "Pasting a key here is only available when this console is served by the local Rove API. Configure the key environment variable below otherwise.",
      apiKeyPlaceholderEdit: "Leave blank to keep the stored key",
      keySaved: "Key verified and stored securely.",
      apiKeyEnv: "API key env name",
      apiKeyEnvHint:
        "When set, the key is read from this environment variable first. You rarely need to change it.",
      keyEnvAdvanced: "Key environment variable",
      defaultModel: "Default model",
      advanced: "Advanced",
      create: "New provider",
      edit: "Edit",
      editProfile: "Edit profile",
      delete: "Delete",
      use: "Use",
      test: "Test connection",
      listModels: "List models",
      save: "Save changes",
      cancel: "Cancel",
      changeKey: "Replace",
      keyHint:
        "The key is stored encrypted on this machine and never enters session records or logs.",
      localDemo: "Local demo",
      localDemoDesc: "Built-in model, no API key or network required",
      draftLabel: "Local OpenAI",
      typeOpenai: "OpenAI",
      typeOpenaiResponses: "OpenAI Responses",
      typeAnthropic: "Anthropic",
      typeOllama: "Ollama",
      connected: "Connected — {{count}} models available",
      keyMissing: "Key is missing",
      unreachable: "Could not reach the provider",
      profileSummary: "{{label}} · {{apiBase}}",
      activeProfile: "Active profile",
      siliconflowQuick: "Add SiliconFlow DeepSeek V3.2",
      activeSelection: "Active selection",
      modeRuntimeDefault: "Runtime default",
      modeSavedProfile: "Saved profile",
      selectProfile: "Select profile…",
      savedProfiles: "Saved profiles",
      usingRuntimeDefault: "Using the API process default provider configuration.",
      labelField: "Label",
      typeField: "Type",
      modelField: "Model",
      editSecure: "Reconfigure secure profile",
      secureOnboarding: "Secure onboarding",
      catalogProfiles: "Shared catalog profiles",
      removeCatalogConfirm: "Remove this profile from the shared catalog?",
      listModelsAction: "List models",
    },
    runtime: {
      connection: "Connection",
      dataStorage: "Data storage",
      runtime: "Runtime",
      sessionRecovery: "Session recovery",
      theme: "Theme",
      workspace: "Workspace",
      status: "Status",
    },
    approval: {
      title: "Approval preferences",
      desc: "Choose which actions ask for your confirmation before running.",
      askMutations: "Ask before file changes and commands",
      askMutationsDesc: "Recommended. Reads stay unasked.",
      askAll: "Ask for every step",
      askAllDesc: "Most cautious; more prompts.",
    },
    export: {
      title: "Export conversation (redacted)",
      desc: "Export this session with sensitive values removed.",
      download: "Download",
    },
  },
  modelControl: {
    change: "Change session model settings",
    provider: "Session provider profile",
    model: "Session model",
    reasoning: "Session reasoning",
    maxSteps: "Session max steps",
    reloadModels: "Reload provider models",
    save: "Save session model",
    saving: "Saving…",
    loadingModels: "Loading provider models…",
    noModels: "Provider returned no models.",
    modelsNotLoaded: "Provider models not loaded",
    runtimeDefault: "Runtime default",
    runtimeProvider: "Runtime provider",
    providerDefault: "Provider default",
    updated: "Session model updated.",
    applyNote: "Changes apply from the next run in this session.",
    saveFailed:
      "The session model settings were not changed. Review the product error and retry.",
  },
  uiSkin: {
    label: "Interface style",
    desc: "Graphite is the default; Warm ivory stays available as an alternative. Applies immediately on this machine.",
    graphite: "Graphite",
    warm: "Warm ivory",
  },
  migration: {
    importing: "Importing your workspace history",
    preparing: "Preparing your workspace history",
    importingBody:
      "Moving browser-saved workspaces and sessions into durable server storage.",
    preparingBody:
      "Checking saved browser data before reading the server catalog.",
    dismiss: "Dismiss import summary",
    imported: "Browser data imported ({{count}} records).",
    importedNoCount: "Browser data imported.",
    storageAuthoritative: "Server storage is now authoritative.",
    verifyTitle: "Import needs verification",
    verifyBody:
      "The server may already have accepted this import. Checking again will replay the exact saved request without duplicating browser data.",
    verifyAction: "Verify import",
    rejectedTitle: "Saved data was not accepted",
    rejectedBody:
      "The server rejected this browser snapshot. Its pending receipt was cleared, so a later retry will validate a fresh snapshot.",
    rejectedAction: "Retry import",
    receiptTitle: "Import receipt changed",
    receiptBody:
      "Another tab or a local storage change replaced the receipt while the server was applying this import.",
    checkAgain: "Check again",
    legacyRepairTitle: "Saved browser data needs repair",
    legacyRepairBody:
      "The saved workspace catalog could not be validated. Correct or clear the invalid browser entry before checking again.",
    receiptRepairTitle: "Import receipt needs repair",
    receiptRepairBody:
      "The saved import receipt is incomplete or invalid. Restore a valid receipt before checking again.",
    storageUnavailableTitle: "Browser storage is unavailable",
    storageUnavailableBody:
      "Rove could not safely persist or verify the import receipt. Allow this site to use browser storage, then check again.",
    lockUnavailableTitle: "Exclusive browser access is unavailable",
    lockUnavailableBody:
      "Rove needs a same-origin browser lock to prevent duplicate imports. Close other Rove tabs or use a browser that supports Web Locks, then check again.",
    unverifiedTitle: "Import could not be verified",
    unverifiedBody:
      "Rove could not establish a trusted server acknowledgement for the saved browser data.",
    assurance:
      "Rove has not deleted your browser-saved workspaces, sessions, or provider references, and will not replace them with an empty server catalog.",
  },
  codeCopy: {
    copy: "Copy code",
    copied: "Copied",
    failed: "Copy failed",
  },
  diff: {
    fallback: "Diff could not be parsed",
    unstructured: "Unstructured diff output",
    canonical: "Workspace change",
    markdown: "Markdown diff",
  },
  errors: {
    bootTitle: "Could not start",
    bootBody: "The product shell failed to finish loading.",
    routeTitle: "Cannot open this session",
    routeBody: "The session route is invalid or no longer exists.",
    code: "code: {{code}}",
  },
  toast: {
    regionLabel: "Notifications",
    dismiss: "Dismiss notification",
    sessionFailed: "Session \"{{title}}\" failed.",
    forkCreated: "Created the forked session \"{{title}}\".",
    revealFailed: "Could not open this path in the file manager.",
    providerTestPassed: "\"{{profile}}\" connected.",
    providerTestIncomplete: "\"{{profile}}\" connected, but no default model was found.",
    providerTestFailed: "\"{{profile}}\" failed to connect: {{error}}",
  },
  inbox: {
    title: "Notification inbox",
    lede: "Failures only.",
    open: "Open the notification inbox",
    openUnread: "Open the notification inbox ({{count}} unread)",
    empty: "Nothing has failed since this page opened.",
    targetMissing: "The session this notification pointed at is no longer in the catalog.",
    clear: "Clear",
    openSession: "Open session",
    openSettings: "Open settings",
    bounded: "Keeps the most recent {{limit}} in memory; reloading the page clears it.",
  },
  boot: {
    loading: "Starting the product shell…",
    checking: "Connecting to the local service…",
  },
  empty: {
    absolutePath: "Absolute path",
    kind: "Kind",
    folder: "Folder",
    repo: "Repo",
    open: "Open workspace",
    browse: "Browse…",
    pickerUnavailable:
      "Native folder picker is unavailable. Enter an absolute path instead.",
    pathRequired: "Enter an absolute path to open.",
    pathPlaceholder: "D:\\path\\to\\project",
  },
  home: {
    prompt: "What should Rove work on?",
    workspaceLead: "Working in",
    chooseWorkspace: "choose a workspace…",
    switcherLabel: "Workspace picker",
    openWorkspace: "Open folder or repo…",
    manualEntry: "Enter a path manually",
    recentSessions: "Recent sessions",
    composerPlaceholder: "Describe a task for Rove…",
    noWorkspaceHint: "Open a workspace first, then send.",
    modelRequired: "Configure a model provider before sending.",
    configureModel: "Provider settings",
  },
  workspace: {
    label: "Workspace",
    newSession: "New session",
    sessions: "Sessions",
    pin: "Pin",
    unpin: "Unpin",
    remove: "Remove",
    add: "Add workspace",
    close: "Close workspaces",
    search: "Search workspaces and sessions",
    searchPlaceholder: "Search names",
    searchScope: "Searches workspace names and asks the server for session titles",
    searchUnavailable: "Server search is unavailable, so only the loaded workspace and session names are filtered.",
    noMatches: "No loaded workspace or session names match.",
    expandProject: "Expand {{name}} sessions",
    collapseProject: "Collapse {{name}} sessions",
    projectActions: "Actions for {{name}}",
    newSessionIn: "New session in {{name}}",
    openDescription: "Open an absolute local folder or repository path. No full-disk scan.",
    running: "Running",
    runningCount: "{{count}} running",
    needsAttention: "Needs attention",
    forked: "Forked session",
    forkedRemovedParent: "Forked session, parent removed",
    parentRemoved: "Parent removed",
    forkPrefix: "Fork",
    sessionsAndBranches: "Sessions and branches",
    pinWorkspace: "Pin workspace",
    unpinWorkspace: "Unpin workspace",
    removeWorkspace: "Remove workspace from list",
    removeWorkspaceArmed: "Confirm removal and its sessions",
    settings: "Settings",
    pathRules: "Path rules",
    pathRulesBody:
      "Add workspaces from the sidebar using an absolute local path. Folder roots expose that directory; Repo roots identify a checkout. Removing an entry removes its sessions but never deletes files from disk.",
    known: "Known workspaces",
    none: "No workspaces are registered yet. Add an absolute Folder or Repo path from the sidebar.",
    removeConfirm:
      "Remove this workspace and its sessions from the catalog? Local files are not deleted.",
    active: " (active)",
    pinned: "Pinned",
    opened: "Opened {{time}}",
    sessionsTitle: "Sessions",
    noSessions: "No sessions",
    noSessionsBody: "No sessions in this workspace.",
    sessionName: "Session name",
    kindRepo: "Repo",
    kindTask: "Task",
    kindFolder: "Folder",
    statusError: "Error",
    updated: "Updated {{time}}",
    durableHistory: "Durable history",
    noCompletedTurn: "No completed turn",
    sessionDeleteConfirm:
      "Delete this session from the durable catalog? Running or unresolved sessions may be rejected by the API.",
    unavailableWorkspace: "Unavailable workspace",
    workspaceGone: "Workspace {{id}} is no longer present in the catalog.",
    sessionCountOne: "{{count}} session",
    sessionCountMany: "{{count}} sessions",
    openPickerFailed: "Failed to open the folder picker.",
    sessionPin: "Pin session",
    sessionUnpin: "Unpin session",
    sessionRename: "Rename session",
    sessionRenameEmpty: "The title cannot be empty.",
    sessionRenameFailed: "Rename failed. The previous title was restored.",
    sessionErrorDot: "The last run of this session failed",
    sessionOutcomeSuccess: "The last run succeeded",
    sessionOutcomeFailed: "The last run failed",
    sessionOutcomeCancelled: "The last run was cancelled",
    sessionCardStatus: "Status",
    sessionCardUpdated: "Last updated",
    sessionCardCreated: "Created",
    sessionCardForkedFrom: "Forked from",
    sessionCardForkPoint: "Fork point",
    sessionCardEvent: "event {{seq}}",
    sessionCardWorkspaceRoot: "Workspace root",
    sessionCardModel: "Model",
    sessionCardReasoning: "Reasoning",
    sessionCardMaxSteps: "Max steps",
    sessionCardLoading: "Loading…",
    sessionCardUnavailable: "—",
    sessionCardMessages: "Messages",
    brandName: "Rove",
    zonePinned: "Pinned",
    zoneProjects: "Projects",
    sortSessions: "Sort sessions",
    sortRecent: "Recent activity",
    sortTitle: "Title A–Z",
    loadMoreSessions: "Show {{count}} more",
    group: {
      today: "Today",
      yesterday: "Yesterday",
      week: "This week",
      older: "Older",
      archived: "Archived",
    },
    sessionActions: "Actions for {{title}}",
    sessionBatchActions: "Actions for {{count}} sessions",
    sessionRenameLabel: "Rename",
    sessionArchive: "Archive",
    sessionRestore: "Restore",
    sessionBranch: "Branch",
    sessionBranchUnavailable:
      "Branching needs an idle session with a finished turn",
    sessionCopyLink: "Copy link",
    sessionExport: "Export evidence",
    sessionDelete: "Delete",
    sessionDeleteArmed: "Delete?",
    sessionBatchArchive: "Archive {{count}} sessions",
    sessionBatchRestore: "Restore {{count}} sessions",
    sessionBatchDelete: "Delete {{count}} sessions",
    sessionBatchDeleteArmed: "Delete {{count}} sessions?",
    sessionClearSelection: "Clear selection",
    sessionQueueCount: "{{count}} queued",
    sessionCardOpen: "Open session",
    openInFileManager: "Open in file manager",
    renameWorkspace: "Rename project",
    removeWorkspaceTitle: "Remove project?",
    removeWorkspaceBody:
      "Remove \"{{name}}\" and its {{count}} sessions from the catalog? Files on disk are not touched.",
    removeWorkspaceConfirm: "Remove project",
    removeWorkspaceDialogHint: "Removes {{count}} sessions from this list",
    version: "v{{version}}",
    versionTitle: "API version {{version}}",
  },
  sessionHoverCard: {
    archived: "Archived",
  },
  tools: {
    lede: "Default tool authorization and execution limits.",
    approvalTitle: "Default approval policy",
    ask: "Ask",
    auto: "Auto",
    never: "Never",
    askDesc: "Pause when a tool requires approval.",
    autoDesc: "Allow runtime-approved tool execution.",
    neverDesc: "Reject tool calls that require approval.",
    maxStepsTitle: "New-session execution limit",
    maxStepsLabel: "Default maximum steps for new sessions",
    saveDefault: "Save default",
  },
  keyboard: {
    lede: "Fast paths for the primary session and navigation actions.",
    title: "Application shortcuts",
    focusComposer: "Focus message composer",
    focusComposerDesc: "Move keyboard focus to the message composer.",
    newSession: "New session",
    newSessionDesc: "Create a session in the active workspace.",
    openSettings: "Open settings",
    openSettingsDesc: "Open General settings from the product shell.",
    toggleInspector: "Toggle run inspector",
    toggleInspectorDesc: "Show or hide the current run inspector.",
    openCommandPalette: "Command palette",
    openCommandPaletteDesc: "Search commands, workspaces, sessions and settings.",
    change: "Change binding",
    unbind: "Unbind",
    reset: "Reset to default",
    awaitingKey: "Press the new key combination… (Escape to cancel)",
    unbound: "Unbound",
    defaultLabel: "Default",
    conflict: "Conflicts with \"{{action}}\". Not saved.",
    reserved: "This combination is reserved by the browser and cannot be used.",
    sendKeyTitle: "Composer send key",
    sendKeyDesc:
      "How a message leaves the composer. Alt+Enter always interjects into the running turn.",
    sendKeyEnter: "Enter sends (Shift+Enter adds a newline)",
    sendKeyModEnter: "Ctrl/Cmd+Enter sends (Enter adds a newline)",
  },
  about: {
    lede: "Live API, product storage, and session recovery health.",
    apiProxy: "API proxy",
    host: "Host",
    apiVersion: "API version",
    runtimeConnection: "Runtime connection",
    adapter: "Adapter",
    workspaceKind: "Workspace kind",
    workspaceIdentity: "Workspace identity",
    filesystemRead: "Filesystem read",
    filesystemWrite: "Filesystem write",
    processRun: "Process run",
    processStdio: "Process stdio",
    processBackground: "Background process",
    processPty: "Pseudo-terminal",
    observations: "Observations",
    available: "Available",
    unavailable: "Unavailable",
    authorized: "Authorized",
    restricted: "Restricted",
    enabled: "Enabled",
    disabled: "Disabled",
    allowed: "Allowed",
    diagnosticOnly: "Diagnostic only",
    selector: "Agent selector",
    workspaceSource: "Workspace source",
    workspaceInstructions: "Workspace instructions",
    remediationProcedures: "Remediation procedures",
    procedureLimit: "Procedure limit",
    resumeStatus: "Recovery status",
    resumeWorkspaces: "Workspaces",
    resumeSessions: "Sessions",
    resumeBound: "Bound sessions",
    resumeRunning: "Running sessions",
    resumeAttention: "Sessions needing attention",
    refreshing: "Refreshing runtime health…",
    storeUnavailable:
      "Data storage is unavailable. Workspace, session, and resume health cannot be read.",
    refresh: "Refresh runtime",
    loading: "Loading runtime health…",
    unavailableTitle: "Runtime information unavailable",
  },
  memory: {
    editTopic: "Edit topic",
    searchPlaceholder: "Title, slug, or description",
    allTypes: "All types",
    allScopes: "All scopes",
    allSources: "All sources",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    refreshTopic: "Refresh topic",
    createTopic: "Create topic",
    count: "{{count}} topics",
    metadata: "Memory topic metadata",
    contentLabel: "Memory topic content",
    listLabel: "Durable memory topics",
    layer: "Storage",
    durable: "Durable",
    created: "Created",
    updated: "Updated",
    notRecorded: "Not recorded",
    noDescription: "No description recorded.",
    metadataTruncated: "Some topic metadata could not be displayed.",
    contentTruncated: "Topic content is incomplete. Editing is disabled to prevent content loss.",
    loadingContent: "Loading topic content…",
    deleteConfirm: "Delete “{{title}}”?",
    deleteWarning: "This permanently removes the topic. This action cannot be undone.",
    confirmDelete: "Confirm delete",
    deleting: "Deleting…",
    listFailed: "Memory topics could not be loaded. Please retry.",
    detailFailed: "The topic could not be loaded. Refresh and retry.",
    deleteFailed: "The topic could not be deleted. Please retry.",
    saveFailed: "The topic was not saved and may have changed. Keep your draft and refresh the topic before retrying.",
    lastLoaded: "Showing the last loaded topics.",
    summary: "{{type}} · {{scope}} · {{confidence}}% confidence",
    type_user: "User",
    type_feedback: "Feedback",
    type_project: "Project",
    type_reference: "Reference",
    scope_global: "Global",
    scope_project: "Project",
    scope_session: "Session",
    source_product_settings: "Settings",
    source_llm_tool: "Agent tool",
    source_other: "Other",
    source_unknown: "Unknown",
    title: "Memory",
    needWorkspace: "Select a workspace to inspect its durable memory.",
    find: "Find topics",
    search: "Search",
    clear: "Clear",
    open: "Open",
    selected: "Selected",
    noMatch: "No durable memory topics match these filters.",
    empty: "No durable memory topics are available.",
    type: "Type",
    scope: "Durable scope",
    source: "Source",
    all: "All",
    slug: "Slug",
    topicTitle: "Title",
    confidence: "Confidence",
    description: "Description",
    content: "Content",
    durableTopics: "Durable topics",
    emptyBody: "No stored body content.",
    newTopic: "New durable topic",
    editTopicTitle: "Edit durable topic",
    deleteTopic: "Delete topic",
    saveTopic: "Save changes",
    testServer: "Test",
    testing: "Testing…",
    loading: "Loading durable memory topics…",
    scopeLabel: "Durable scope",
  },
  mcp: {
    title: "MCP servers",
    addServer: "Add server",
    addServerTitle: "Add MCP server",
    editServerTitle: "Edit {{name}}",
    serverName: "Server name",
    timeout: "Connection timeout (ms)",
    enabled: "Enabled",
    required: "Required at startup",
    command: "Command",
    args: "Arguments (one per line)",
    envNames: "Environment names (one per line)",
    workspaceServers: "Workspace servers",
    loading: "Loading MCP servers…",
    none: "No MCP servers in this workspace.",
    removeConfirm: "Remove {{name}} from this workspace?",
    remove: "Remove",
    transport: "MCP transport",
    refresh: "Refresh MCP servers",
  },
  trust: {
    title: "Project trust",
    capabilities: "Capabilities",
    changed: "Changed",
    granted: "Granted",
    refresh: "Refresh project trust",
  },
  richText: {
    linkOpenUnsupported: "The current host cannot open external links.",
    linkOpenBlocked: "Blocked that link: only http and https links are allowed.",
    linkOpenFailed: "The system could not open that link.",
    loadingCode: "Loading code renderer…",
    loadingDiagram: "Loading diagram renderer…",
    renderingDiagram: "Rendering diagram…",
    diagramLabel: "Mermaid diagram",
    diagramUnavailable: "Diagram unavailable",
    diagramTooLarge: "Diagram source exceeds the browser rendering limit.",
    diagramRenderFailed: "Diagram could not be rendered.",
  },
};

export default enUS;

