const zhCN = {
  desktopProviders: {
    description: "桌面版将密钥安全保存在 Windows 凭据管理器中，服务配置不包含密钥明文。",
    defaultSelection: "正在使用默认模型服务配置。",
    onboardingHint: "继续后将在系统安全窗口中输入密钥。连接测试成功后才会保存配置。",
    preset: "使用 SiliconFlow 预设",
    compatible: "兼容 OpenAI",
    credentialHint: "密钥由 Windows 安全窗口收集，不会进入网页表单或浏览器存储。",
    verifying: "正在验证…",
    saveVerify: "保存并验证",
    verified: "已验证并保存 {{label}}，当前使用 {{model}}。",
    connected: "{{label}} 连接成功，可读取模型列表。",
    modelsLoaded: "已为 {{label}} 加载 {{count}} 个模型。",
    selected: "已选择 {{label}} · {{model}}。",
    removed: "已移除模型服务配置。",
    probeSummary: "连接测试：{{count}} 个模型可用 · 逐步显示回复：{{streaming}} · 使用工具：{{tools}} · 用量统计：{{usage}}",
    supported: "支持",
    unsupported: "不支持",
    models: "可用模型：{{models}}",
    empty: "尚未配置模型服务，请先在上方添加。",
    active: "（当前使用）",
    noDefaultModel: "未设置默认模型",
    selecting: "正在选择…",
    reconfigure: "重新配置",
    remove: "移除",
    credentialKeyring: "密钥保存在系统中",
    credentialEnv: "密钥来自环境变量",
    credentialFile: "密钥来自本地文件",
    credentialNone: "未配置密钥",
  },
  artifactLabels: {
    report: "运行报告",
    task_state: "任务进度",
    trace: "活动记录",
    registered: "运行生成的文件",
    tool_artifact: "工具生成的文件",
    available: "可用",
    cleaned: "内容已清理",
    invalid: "内容无法验证",
    too_large: "文件较大，请下载查看",
  },
  review: {
    title: "只读审查",
    refresh: "刷新审查",
    cancel: "取消审查",
    loading: "正在加载审查…",
    empty: "暂无审查记录",
    emptyBody: "从输入框开始审查，检查 Git 目标而不修改文件。",
    run: "审查记录",
    target: "目标",
    files: "文件",
    findings: "发现的问题",
    unchecked: "未检查",
    warnings: "警告",
    passBody: "未报告需要处理的问题。",
    loadingFindings: "正在加载问题…",
    unavailableFindings: "暂时无法获取问题详情。",
    openFiles: "在文件中打开",
    more: "加载更多问题",
    partialBody: "部分内容未完成检查，请先核对审查范围再采取行动。",
    staleBody: "目标已更改或需要关注，请对当前文件重新开始审查。",
    unavailableBody: "审查目标或服务不可用。",
    cancelledBody: "审查已取消，尚未完成。",
    errorBody: "审查失败，对话未被更改。",
    error: "无法完成审查操作，请刷新后重试。",
    warningBody: "审查有警告，请核对检查范围后再采用结果。",
    unknown: "未知",
    status_queued: "排队中",
    status_running: "审查中",
    status_pass: "未发现问题",
    status_findings: "发现问题",
    status_partial: "部分完成",
    status_stale: "目标已更改",
    status_needs_attention: "需关注",
    status_unavailable: "不可用",
    status_cancelled: "已取消",
    status_error: "失败",
  },
  chrome: {
    loadError: "无法完成操作，请刷新后重试。",
    partial: "部分记录未能加载。",
    download: "下载 {{name}}",
    previewUnavailable: "此类型暂不支持预览。",
    invalidContent: "内容无法安全预览。",
    cleaned: "产物内容已清理。",
    format: "格式",
    offlineHtml: "离线 HTML",
    refreshDiff: "刷新差异",
    noPatch: "没有记录差异内容。",
    binary: "二进制文件",
    truncated: "部分内容",
    fullPatch: "完整差异",
    summaryOnly: "仅摘要",
    directory: "文件夹",
    loadMore: "加载更多",
    scanLimited: "目录较大，仅显示安全范围内的结果。",
    advanced: "高级选项",
    cancelEdit: "取消编辑",
    models: "可用模型（{{count}}）",
    removeProvider: "移除该模型服务配置？此操作不会删除会话。",
    settingsError: "设置操作未完成，请检查当前设置后重试。",
    providerError: "模型服务操作未完成，请检查连接与配置后重试。",
  },
  common: {
    retry: "重试",
    cancel: "取消",
    save: "保存",
    saving: "保存中…",
    saved: "已保存",
    close: "关闭",
    back: "返回",
    loading: "加载中…",
    none: "暂无",
    noSavedProfiles: "尚未保存服务配置。",
    more: "更多",
    actions: "操作",
    dismiss: "知道了",
    copy: "复制",
    copied: "已复制",
  },
  connection: {
    ok: "API 已连接",
    error: "API 无法连接",
    checking: "正在检查 API…",
  },
  theme: {
    toLight: "切换到浅色主题",
    toDark: "切换到深色主题",
  },
  locale: {
    label: "语言",
    zhCN: "中文",
    enUS: "English",
  },
  nav: {
    settings: "设置",
    backToChat: "返回会话",
    workspace: "工作区",
    expandWorkspace: "展开工作区列表",
    collapseWorkspace: "收起工作区列表",
    inspector: "详情",
    expandInspector: "展开详情面板",
    collapseInspector: "收起详情面板",
    closeInspector: "关闭详情",
    newSession: "新会话",
    searchWorkspace: "搜索会话",
  },
  chat: {
    responding: "正在回复…",
    assistant: "助手",
    you: "你",
    send: "发送",
    stop: "停止",
    placeholder: "输入消息，Enter 发送，Shift+Enter 换行",
    loadOlder: "加载更早的轮次",
    restoring: "正在恢复此会话…",
    restorePartialTitle: "部分较早的消息未能恢复",
    restorePartial: "部分较早的消息未能恢复，新消息不受影响。",
    restoreFailed: "会话记录恢复失败",
    restoreError: "空历史不会被伪造。",
    restoreRetry: "重试恢复",
    startNewSession: "开始新会话",
    emptyTranscript: "发送一条消息，开始本会话中的本轮任务。",
    approve: "批准",
    reject: "拒绝",
    onlyThisTime: "仅本次",
    queue: "排队发送",
    revoke: "撤销",
    promote: "立即发送",
    disabledRestoring: "正在完成会话恢复…",
    disabledSettings: "会话设置加载中…",
    disabledRestoreError: "请先重试恢复会话记录。",
    disabledRoute: "请先解决会话路由问题。",
    model: "模型",
    mode: "模式",
    review: "审查",
    turn: "第 {{n}} 轮",
    currentTurn: "当前轮次",
    inputSubmitted: "输入已提交",
    inputClosed: "输入已关闭",
    revokeTitle: "撤销该消息",
    evidence: "消息用量与上下文",
    reviewTarget: "目标",
    reviewUncommitted: "未提交的更改",
    reviewBase: "基准版本",
    reviewCommit: "提交",
    reviewStart: "开始审查",
    reviewStarting: "正在开始…",
    reviewRevision: "审查版本",
    reviewBasePlaceholder: "基准引用，例如 main",
    reviewCommitPlaceholder: "提交 SHA",
  },
  inspector: {
    title: "详情",
    tabRun: "活动",
    tabReview: "审查",
    files: "文件",
    filesLoading: "正在加载文件…",
    artifacts: "产物",
    artifactsLoading: "正在加载产物…",
    artifactsNone: "暂无产物记录。",
    artifactsRefresh: "刷新产物",
    filesParent: "返回上级目录",
    diff: "差异",
    diffLoading: "正在加载差异…",
    diffNone: "没有记录工具或 Git 变更。",
    usageEvidence: "消息用量与上下文",
    compacted: "已精简",
    historyIncluded: "保留 {{included}} 条 / 精简 {{dropped}} 条",
    emptyTitle: "暂无进行中的运行",
    emptyBody: "发送一条消息开始本轮对话。计划、工具与审批会显示在这里。",
    working: "进行中…",
    streaming: "正在处理，工具与审批会随进度更新。",
    errorTitle: "运行中断",
    summaryTitle: "本次运行",
    statusQueued: "排队中",
    statusRunning: "运行中",
    statusWaitingApproval: "等待批准",
    statusCompleted: "已完成",
    statusFailed: "失败",
    statusCanceled: "已取消",
    model: "模型",
    duration: "用时",
    startedAt: "开始于",
    usage: "用量",
    cost: "费用",
    tokens: "{{count}} tokens",
    timeline: "时间线",
    timelineStart: "开始处理你的请求",
    timelineTools: "使用了 {{count}} 个工具",
    timelineApproval: "等待你的批准",
    timelineComplete: "运行完成",
    timelineFailed: "运行失败",
    timelineCanceled: "运行已取消",
    filesTitle: "本次改动的文件",
    filesNone: "本轮没有文件改动。",
    planTitle: "计划",
    planWaiting: "正在等待计划…",
    planNone: "本轮没有计划。",
    approvalsTitle: "审批",
    approvalsNone: "没有待处理的审批。",
    approvalsWaiting: "等待中",
    toolsTitle: "工具",
    toolsNone: "尚无工具调用。",
    toolsWaiting: "等待工具调用…",
    usageTitle: "用量",
    prompt: "输入",
    completion: "输出",
    cached: "缓存",
    total: "合计",
    sessionTotal: "会话合计",
    contextEstimate: "上下文估计",
    compactedNotice: "为腾出空间，较早的对话已自动精简。",
    restorePartial: "部分较早的消息未能恢复，完整记录已保存在本地。",
    usageUnavailable: "用量信息暂不可用",
    notLoaded: "未加载",
    notAvailable: "不可用",
  },
  settings: {
    title: "设置",
    lede: "管理模型接入、审批偏好与界面选项。所有配置保存在本机。",
    sectionGeneral: "通用",
    sectionProviders: "模型服务",
    sectionTools: "工具与审批",
    sectionWorkspace: "工作区路径",
    sectionMemory: "记忆",
    sectionSessions: "会话",
    sectionKeyboard: "键盘快捷键",
    sectionAdvanced: "高级",
    sectionAbout: "关于",
    generalLede: "外观、语言与界面风格。",
    advancedLede: "诊断与迁移相关入口已移出产品界面。",
    advancedEmpty:
      "基准评测请使用命令行 `rove-bench`。工作台与诊断页仅在开发模式可用，生产构建不可达。",
    general: {
      appearance: "外观",
      theme: "主题",
      themeLight: "浅色",
      themeDark: "深色",
      language: "语言",
      languageDesc: "界面显示语言，立即生效并保存在本机。",
    },
    providers: {
      title: "模型服务",
      desc: "选择会话使用的模型来源。密钥保存在系统凭据管理器中，不会显示明文。",
      profile: "服务配置",
      type: "类型",
      label: "名称",
      mode: "模式",
      model: "模型",
      apiBase: "API 地址",
      apiKey: "API 密钥",
      apiKeyEnv: "密钥环境变量名",
      apiKeyEnvHint: "设置后优先从环境变量读取密钥，一般无需修改。",
      keyEnvAdvanced: "密钥环境变量名",
      defaultModel: "默认模型",
      advanced: "高级选项",
      create: "新建服务",
      edit: "编辑",
      editProfile: "编辑服务",
      delete: "删除",
      use: "使用",
      test: "测试连接",
      listModels: "列出模型",
      save: "保存更改",
      cancel: "取消",
      changeKey: "更换",
      keyHint: "密钥加密保存在本机，仅在本机使用，不会随会话记录或日志泄露。",
      localDemo: "本地演示",
      localDemoDesc: "内置模型，无需联网与密钥",
      typeOpenai: "OpenAI",
      typeOpenaiResponses: "OpenAI Responses",
      typeAnthropic: "Anthropic",
      typeOllama: "Ollama",
      connected: "已连接 — {{count}} 个模型可用",
      keyMissing: "密钥缺失",
      unreachable: "无法连接该服务",
      profileSummary: "{{label}} · {{apiBase}}",
      activeProfile: "当前使用的配置",
      siliconflowQuick: "快速添加 SiliconFlow DeepSeek V3.2",
      activeSelection: "当前选择",
      modeRuntimeDefault: "运行时默认",
      modeSavedProfile: "已保存配置",
      selectProfile: "选择配置…",
      savedProfiles: "已保存的配置",
      usingRuntimeDefault: "正在使用 API 进程的默认模型配置。",
      labelField: "名称",
      typeField: "类型",
      modelField: "模型",
      editSecure: "重新配置安全凭据",
      secureOnboarding: "安全接入",
      catalogProfiles: "共享目录配置",
      removeCatalogConfirm: "从共享目录中移除该配置？",
      listModelsAction: "列出模型",
    },
    runtime: {
      connection: "连接",
      dataStorage: "数据存储",
      runtime: "运行时",
      sessionRecovery: "会话恢复",
      theme: "主题",
      workspace: "工作区",
      status: "状态",
    },
    approval: {
      title: "审批偏好",
      desc: "控制哪些操作需要你确认后才会执行。",
      askMutations: "修改文件与运行命令时询问",
      askMutationsDesc: "推荐。读取文件不询问。",
      askAll: "每一步都询问",
      askAllDesc: "最稳妥，交互会变多。",
    },
    export: {
      title: "导出对话（脱敏）",
      desc: "导出当前会话内容，敏感信息会被移除。",
      download: "下载",
    },
  },
  modelControl: {
    change: "更改会话模型设置",
    close: "关闭模型控件",
    provider: "会话模型服务",
    model: "会话模型",
    reasoning: "会话推理设置",
    maxSteps: "会话最大步数",
    reloadModels: "重新加载模型列表",
    save: "保存会话模型",
    saving: "保存中…",
    loadingModels: "正在加载模型列表…",
    noModels: "服务未返回模型。",
    modelsNotLoaded: "尚未加载模型列表",
    runtimeDefault: "运行时默认",
    runtimeProvider: "运行时服务",
    providerDefault: "服务默认",
    updated: "会话模型已更新。",
    applyNote: "更改将在本会话的下一轮生效。",
    saveFailed: "会话模型设置未更改。请查看产品错误后重试。",
  },
  uiSkin: {
    label: "界面风格",
    desc: "对比两套视觉方案后再定稿。选择会立即生效并保存在本机。",
    warm: "暖米色",
    cool: "冷色精修",
  },
  migration: {
    importing: "正在导入工作区历史",
    preparing: "正在准备导入工作区历史",
    importingBody: "正在把浏览器中保存的工作区与会话迁入服务端持久存储。",
    preparingBody: "正在检查已保存的浏览器数据，然后读取服务端目录。",
    dismiss: "关闭导入摘要",
    imported: "浏览器数据已导入（{{count}} 条记录）。",
    importedNoCount: "浏览器数据已导入。",
    storageAuthoritative: "服务端存储现已生效。",
    verifyTitle: "导入需要确认",
    verifyBody: "服务端可能已经接受过这次导入。再次检查会重放同一请求，不会重复导入浏览器数据。",
    verifyAction: "确认导入",
    rejectedTitle: "保存的数据未被接受",
    rejectedBody: "服务端拒绝了该浏览器快照。待处理回执已清除，可稍后重试新快照。",
    rejectedAction: "重试导入",
    receiptTitle: "导入回执已变化",
    receiptBody: "另一个标签页或本地存储变更在服务端应用导入时替换了回执。",
    checkAgain: "再次检查",
    legacyRepairTitle: "浏览器数据需要修复",
    legacyRepairBody: "无法校验已保存的工作区目录。请先修正或清除无效的浏览器条目，然后再次检查。",
    receiptRepairTitle: "导入回执需要修复",
    receiptRepairBody: "保存的导入回执不完整或无效。请先恢复有效回执，然后再次检查。",
    storageUnavailableTitle: "浏览器存储不可用",
    storageUnavailableBody: "rove 无法安全地保存或校验导入回执。请允许本站使用浏览器存储，然后再次检查。",
    lockUnavailableTitle: "无法独占浏览器访问",
    lockUnavailableBody: "rove 需要同源浏览器锁以避免重复导入。请关闭其他 rove 标签页，或改用支持 Web Locks 的浏览器，然后再次检查。",
    unverifiedTitle: "导入无法确认",
    unverifiedBody: "rove 未能为已保存的浏览器数据建立可信的服务端确认。",
    assurance:
      "rove 尚未删除浏览器中保存的工作区、会话或模型服务引用，也不会用空的服务端目录替换它们。",
  },
  codeCopy: {
    copy: "复制代码",
    copied: "已复制",
    failed: "复制失败",
  },
  diff: {
    fallback: "无法解析差异",
    unstructured: "非结构化差异输出",
    canonical: "工作区变更",
    markdown: "Markdown 差异",
  },
  errors: {
    bootTitle: "启动失败",
    bootBody: "产品界面未能完成加载。",
    routeTitle: "无法打开该会话",
    routeBody: "会话路由无效或已被移除。",
    code: "代码：{{code}}",
  },
  boot: {
    loading: "正在启动产品界面…",
    checking: "正在连接本地服务…",
  },
  empty: {
    title: "打开工作区以开始",
    body: "rove 在真实的本地目录上运行。打开文件夹或仓库路径后，即可在会话中对话。",
    absolutePath: "绝对路径",
    kind: "类型",
    folder: "文件夹",
    repo: "仓库",
    open: "打开工作区",
    browse: "浏览…",
    browseFolder: "打开文件夹",
    browseFolderHint: "点击后会弹出系统文件夹选择窗口；也可以在下方粘贴绝对路径。",
    pickerUnavailable: "本机文件夹选择不可用，请手动输入绝对路径。",
    configureProvider: "配置模型服务",
    recents: "最近打开",
    pathRequired: "请输入要打开的绝对路径。",
  },
  workspace: {
    label: "工作区",
    newSession: "新会话",
    sessions: "会话",
    pin: "固定",
    unpin: "取消固定",
    remove: "移除",
    add: "添加工作区",
    close: "关闭工作区列表",
    search: "搜索工作区与会话",
    searchPlaceholder: "搜索会话",
    running: "运行中",
    runningCount: "{{count}} 个会话运行中",
    needsAttention: "需关注",
    forked: "派生会话",
    forkedRemovedParent: "派生会话（父会话已移除）",
    parentRemoved: "父会话已移除",
    forkPrefix: "派生",
    sessionsAndBranches: "会话与分支",
    pinWorkspace: "固定工作区",
    unpinWorkspace: "取消固定工作区",
    removeWorkspace: "从列表移除工作区",
    settings: "设置",
    pathRules: "路径规则",
    pathRulesBody:
      "从侧栏添加本地绝对路径。文件夹根暴露该目录；仓库根标识代码检出。移除条目会从目录中删除其会话，但不会删除磁盘上的文件。",
    known: "已知工作区",
    none: "尚未注册工作区。请从侧栏添加绝对路径。",
    removeConfirm: "从目录中移除该工作区及其会话？本地文件不会被删除。",
    active: "（当前）",
    pinned: "已固定",
    opened: "打开于 {{time}}",
    sessionsTitle: "会话",
    noSessions: "暂无会话",
    noSessionsBody: "该工作区下还没有会话。",
    sessionName: "会话名称",
    openPickerFailed: "无法打开文件夹选择器。",
  },
  tools: {
    lede: "默认工具授权与执行上限。",
    approvalTitle: "默认审批策略",
    ask: "询问",
    auto: "自动",
    never: "从不",
    askDesc: "工具需要审批时暂停。",
    autoDesc: "允许运行时已批准的工具执行。",
    neverDesc: "拒绝需要审批的工具调用。",
    maxStepsTitle: "新会话执行上限",
    maxStepsLabel: "新会话默认最大步数",
    saveDefault: "保存默认值",
  },
  keyboard: {
    lede: "会话与导航的快捷操作。",
    title: "应用快捷键",
    focusComposer: "聚焦输入框",
    focusComposerDesc: "将键盘焦点移到消息输入框。",
    newSession: "新会话",
    newSessionDesc: "在当前工作区创建会话。",
    openSettings: "打开设置",
    openSettingsDesc: "从产品外壳打开通用设置。",
    toggleInspector: "切换详情面板",
    toggleInspectorDesc: "显示或隐藏当前运行详情。",
  },
  about: {
    lede: "本地 API、产品存储与会话恢复健康状况。",
    apiProxy: "API 代理",
    host: "宿主",
    apiVersion: "API 版本",
    runtimeConnection: "运行时连接",
    adapter: "适配器",
    workspaceKind: "工作区类型",
    workspaceIdentity: "工作区标识",
    filesystemRead: "读取文件",
    filesystemWrite: "写入文件",
    processRun: "运行进程",
    processStdio: "进程标准流",
    processBackground: "后台进程",
    processPty: "伪终端",
    observations: "观察记录",
    available: "可用",
    unavailable: "不可用",
    authorized: "已授权",
    restricted: "受限",
    enabled: "已启用",
    disabled: "已禁用",
    allowed: "允许",
    diagnosticOnly: "仅诊断",
    selector: "Agent 选择器",
    workspaceSource: "工作区指令来源",
    workspaceInstructions: "工作区指令",
    remediationProcedures: "修复流程",
    procedureLimit: "流程选择上限",
    resumeStatus: "恢复状态",
    resumeWorkspaces: "工作区数",
    resumeSessions: "会话数",
    resumeBound: "已绑定会话",
    resumeRunning: "运行中会话",
    resumeAttention: "需关注会话",
    refreshing: "正在刷新运行状态…",
    storeUnavailable: "数据存储不可用。无法读取工作区、会话与恢复状态。",
    refresh: "刷新运行状态",
    loading: "正在加载运行状态…",
    unavailableTitle: "暂时无法获取运行信息",
  },
  memory: {
    editTopic: "编辑主题",
    searchPlaceholder: "标题、标识或说明",
    allTypes: "全部类型",
    allScopes: "全部作用域",
    allSources: "全部来源",
    refresh: "刷新",
    refreshing: "刷新中…",
    refreshTopic: "刷新主题",
    createTopic: "创建主题",
    count: "{{count}} 个主题",
    metadata: "主题信息",
    contentLabel: "记忆主题内容",
    listLabel: "持久记忆主题",
    layer: "存储",
    durable: "持久记忆",
    created: "创建时间",
    updated: "更新时间",
    notRecorded: "未记录",
    noDescription: "暂无说明。",
    metadataTruncated: "部分主题信息未能显示。",
    contentTruncated: "主题内容未完整加载，为防止丢失内容，暂时无法编辑。",
    loadingContent: "正在加载主题内容…",
    deleteConfirm: "删除“{{title}}”？",
    deleteWarning: "此操作将永久删除该主题，无法撤销。",
    confirmDelete: "确认删除",
    deleting: "删除中…",
    listFailed: "无法加载记忆主题，请重试。",
    detailFailed: "无法加载该主题，请刷新后重试。",
    deleteFailed: "无法删除该主题，请重试。",
    saveFailed: "主题未保存，可能已被更改。请保留草稿并刷新主题后重试。",
    lastLoaded: "当前显示上次加载的主题。",
    summary: "{{type}} · {{scope}} · 置信度 {{confidence}}%",
    type_user: "用户",
    type_feedback: "反馈",
    type_project: "项目",
    type_reference: "参考",
    scope_global: "全局",
    scope_project: "项目",
    scope_session: "会话",
    source_product_settings: "设置",
    source_llm_tool: "助手工具",
    source_other: "其他",
    source_unknown: "未知",
    title: "记忆",
    needWorkspace: "请先选择工作区以查看其持久记忆。",
    find: "查找主题",
    search: "搜索",
    clear: "清除",
    open: "打开",
    selected: "已选中",
    noMatch: "没有符合筛选条件的持久记忆主题。",
    empty: "暂无持久记忆主题。",
    type: "类型",
    scope: "作用域",
    source: "来源",
    all: "全部",
    slug: "标识",
    topicTitle: "标题",
    confidence: "置信度",
    description: "说明",
    content: "内容",
    durableTopics: "持久主题",
    emptyBody: "尚无内容。",
    newTopic: "新建持久主题",
    editTopicTitle: "编辑持久主题",
    deleteTopic: "删除主题",
    saveTopic: "保存更改",
    testServer: "测试连接",
    testing: "测试中…",
    loading: "正在加载持久记忆主题…",
    scopeLabel: "作用域",
  },
  mcp: {
    title: "MCP 服务",
    addServer: "添加服务",
    addServerTitle: "添加 MCP 服务",
    editServerTitle: "编辑 {{name}}",
    serverName: "服务名称",
    timeout: "连接超时（毫秒）",
    enabled: "已启用",
    required: "启动时必需",
    command: "命令",
    args: "参数（每行一个）",
    envNames: "环境变量名（每行一个）",
    workspaceServers: "工作区服务",
    loading: "正在加载 MCP 服务…",
    none: "该工作区暂无 MCP 服务。",
    removeConfirm: "从该工作区移除 {{name}}？",
    remove: "移除",
  },
  trust: {
    title: "项目信任",
    capabilities: "能力",
    changed: "已更改",
    granted: "已授权",
  },
};

export type CopyDictionary = typeof zhCN;

export default zhCN;


